# Version of the agent configuration standard
version = "1.0"

# Default model for all agents
model = "claude-4-sonnet"

# 
instructions = """
You are working on Health Insurance, landing pages for an affiliate.


"""

# Import all agent configurations
imports = [
    "agents/emily.toml",
    "agents/morgan.toml",
    "agents/casey.toml",
    "agents/jules.toml",
    "agents/riley.toml",
    "agents/shane.toml",
    "agents/alex.toml",
    "agents/quinn.toml",
    "agents/taylor.toml",
    "agents/atlas.toml",
    "agents/blake.toml",
    "agents/hudson.toml",
    "agents/cora.toml",
    "agents/clive.toml",
    "agents/frank.toml",
    "agents/jason.toml",
]